network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true
    ens4:
      dhcp4: false
      addresses: ["192.168.1.100/24"]
      routes:
        - to: default
          via: 192.168.1.1
          metric: 100
