network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true
    ens4:
      dhcp4: false
      addresses: ["172.16.0.11/16"]
      routes:
        - to: default
          via: 172.16.0.1
          metric: 100
