#cloud-config

# Nombre del host
hostname: cliente2

# Actualizar paquetes
package_update: true
package_upgrade: true

# Usuarios
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - public_key
chpasswd:
  expire: False
  users:
    - name: debian
      password: debian
      type: text
